### ISSUE TITLE
RPi-PXE.sh: line 390: [: too many arguments

### ISSUE THREAD

**Issue by MisterDeeds** [Tech-Byte-Tips/RPi-PXE#2]
Dear PREngineer

Thanks alot for the awesome script and your work!

Under "Provision a new Pi using an image" I get the following message at the end:

`RPi-PXE.sh: line 390: [: too many arguments`

I use the following Bash version:
```
echo "${BASH_VERSION}"
5.2.15(1)-release
```

![image](https://github.com/Tech-Byte-Tips/RPi-PXE/assets/8822811/95ece329-f5ba-4d86-892e-1afa2bd18c3a)

I was able to fix it by replacing `-or` with `||`.

`if [ $RESTRICT == 'y' ] || [ $RESTRICT == 'Y' ]; then`

![image](https://github.com/Tech-Byte-Tips/RPi-PXE/assets/8822811/bcb8fb17-af3c-40a6-93ed-e200fad4f2c8)

Thanks again and best regards

**Comment by PREngineer** [comment]
Hey @MisterDeeds,

Weird, I don't get that error.  I'll use that for the latest update.  I'm currently working on a fix for the latest OS not working because of changes in the boot files.

Thanks.

**Comment by PREngineer** [comment]
Closing this Issue as I've updated line 390 to use the "||" operator.
